name: Golang CI
on:
  push:
    tags: [v*.*.*]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [master]

jobs:
  tests:
    strategy:
      matrix:
        go-version: [1.24.x, 1.25.x, 1.26.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      CGO_ENABLED: 0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run Vet
        run: go vet ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run Race 1 CPU
        run: go test -v -cpu=1 -short -race ./...

      - name: Run Race 4 CPU
        run: go test -v -cpu=4 -short -race ./...

  coverage:
    strategy:
      matrix:
        go-version: [1.26.x]
        os: [ubuntu-latest]
    env:
      CGO_ENABLED: 0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests and generate coverage report
        run: |
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          file: coverage.out

  fuzzing:
    strategy:
      matrix:
        go-version: [1.26.x]
        os: [ubuntu-latest]
    env:
      CGO_ENABLED: 0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run FuzzParse
        run: go test -v -fuzz=FuzzParse -fuzztime=30s ./...

      - name: Run FuzzFormat
        run: go test -v -fuzz=FuzzFormat -fuzztime=30s ./...
